version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: construction_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/construction_crm
      SECRET_KEY: your-secret-key-change-this
      DEBUG: "True"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: